# Plan operativo — ES. Contenido copiado literalmente de
# assets/plan-operativo-acero-es.pdf (8 páginas). **texto** = negrita del original.
# Este archivo NUNCA se publica: construir.py lo renderiza y lo cifra.

PLAN = [
  ("cover", {
    "brand": "PRESSTON STRATEGIC PARTNERS",
    "eyebrow": "PLAN OPERATIVO",
    "title": ["LÍNEA REPLICABLE", "DE IMPORTACIÓN", "Y DISTRIBUCIÓN"],
    "sub": "Primera unidad · producto de ferretería",
    "figures": [
      ("Capital solicitado", "USD 120,000", None),
      ("Volumen base", "24 contenedores al año", None),
      ("Utilidad bruta proyectada", "USD 302,416", "35%"),
      ("Resultado antes de impuestos", "USD 164,059", "1.37x"),
      ("Resultado después de impuestos", "USD 126,059", "1.05x"),
    ],
    "foot": "DOCUMENTO CONFIDENCIAL · CÍRCULO PRIVADO DE SOCIOS",
  }),

  ("sec", "01", "QUÉ SE ESTÁ FINANCIANDO"),
  ("lead", "Esto no es un negocio de 24 contenedores. Es una línea de importación que se monta una vez y después se replica."),
  ("p", "Los 24 contenedores del primer año no son la meta. Son el volumen mínimo que ya sabemos colocar, y sobre el que está construido todo este plan. Se proyecta sobre esa base porque es la única probada, no porque sea el límite."),
  ("p", "**Lo que cuesta montar la línea se paga una sola vez:** la relación con la fábrica, la fianza aduanera, el agente de aduana, el sistema de trazabilidad, la contabilidad y el cumplimiento. Esa estructura sirve igual para 24 contenedores que para 100."),
  ("p", "**Lo que se replica es barato:** espacio de bodega, un vehículo, dos personas."),
  ("p", "Por eso cada mercado nuevo cuesta menos que el anterior y rinde más. Ahí está el negocio de largo plazo, no en el primer año."),
  ("call", "FUNCIÓN DE LA PRIMERA UNIDAD", ["Construir el historial de compra que desbloquea crédito del proveedor, probar la operación a volumen sostenido, y generar el flujo que financia la segunda. **No hay una segunda solicitud de capital.**"], ""),

  ("sec", "02", "CÓMO SE GANA EL DINERO"),
  ("p", "Compramos de fábrica en origen, importamos por nuestro puerto de entrada, y vendemos."),
  ("unit", "POR CONTENEDOR", ["872 cajas", "Cuesta 23,269 puesto en puerto", "Se vende en 36,232"], "Deja 12,963"),
  ("p", "Ese ciclo ya se ejecutó completo: se compró, se importó, se despachó en aduana, se vendió y se cobró."),
  ("p", "**Vendemos un dólar por debajo del mercado y aun así ganamos 35% bruto.** Podemos hacerlo porque no cargamos las estructuras fijas de un distribuidor tradicional."),

  ("sec", "03", "EL PRODUCTO"),
  ("table", ["PRODUCTO", "CAJAS", "KG / CAJA", "PUESTO EN PUERTO", "PRECIO", "MARGEN"], "lrrrrr",
    [["Línea A", "480", "21.40", "28.84", "42.00", "31%"],
     ["Línea B", "196", "20.69", "27.88", "42.00", "34%"],
     ["Línea C", "196", "15.00", "20.22", "40.00", "49%"]], {}),
  ("caption", "Se compra por kilo y se vende por caja. El precio se negocia en un solo número: dólares por kilo FOB."),

  ("sec", "04", "DÓNDE SE VENDE"),
  ("p", "**Venta directa — 80% del volumen.** El cliente llega a la bodega y compra, o le llevamos el producto a la obra dentro de un radio de 60 millas. Se cobra al momento y queda el margen completo, sin comisión de nadie."),
  ("p", "**Mayoreo — 20% del volumen.** Se entrega producto a distribuidores con pago contra entrega. No hay crédito ni consignación: el cobro es inmediato, igual que en la venta directa. Rinde algo menos por caja, pero no depende de nuestra estructura operativa — si la venta directa se interrumpe, este canal sigue moviendo producto."),
  ("table", ["CANAL", "%", "VENTA ANUAL"], "lrr",
    [["Directa", "80%", "695,654"],
     ["Mayoreo", "20%", "173,914"]], {"hl": [0]}),
  ("caption", "Mismo precio en los dos canales."),

  ("sec", "05", "POR QUÉ CUESTA MENOS OPERAR"),
  ("p", "**Bodega compartida.** No se paga renta de nave industrial. Se paga el espacio que se usa y crece con el volumen. Un distribuidor tradicional carga ese costo fijo desde el primer día, lo use o no."),
  ("p", "**Flota mixta.** Vehículo propio para la ruta base, contratistas por entrega en los picos. El costo de entrega sube y baja con el volumen en lugar de quedarse fijo. En un mes bajo no se paga flota parada."),
  ("p", "**Equipo formado adentro.** Se contrata gente joven que quiere aprender un oficio y se le forma en el ciclo completo: inventario, atención, entrega, y reparación y mecánica básica del producto. Cuesta menos que contratar perfiles hechos, y da personal que entiende el producto y resuelve en campo."),
  ("call", None, ["**Esto no es recorte. Es la estructura, y es lo que sostiene el precio.**"], ""),

  ("sec", "06", "QUÉ CUESTA TRAER UN CONTENEDOR"),
  ("sub", "A 0.78 USD/KG FOB"),
  ("table", ["CONCEPTO", "USD"], "lr",
    [["Mercancía", "13,467"],
     ["Arancel", "6,733"],
     ["Tasas aduanales", "64"],
     ["Flete marítimo", "2,600"],
     ["Despacho, agente, maniobras, seguro", "405"],
     ["Puesto en puerto", "23,269"]], {"strong": [5]}),
  ("p", "**El arancel pesa 2.6 veces más que el flete.** Por eso cada centavo negociado en el precio de compra vale más de lo que parece: se ahorra el centavo y también el arancel sobre ese centavo. Cada dólar recortado del FOB vale 1.50 en costo real."),
  ("p", "Negociar el precio de compra es la prioridad número uno, por encima de cualquier otro ahorro."),
  ("call", "VALE 1,244 POR CONTENEDOR SIN NEGOCIAR NADA", ["Si el flete marítimo viene identificado por separado en la factura, se deduce del valor aduanero y no paga arancel. Si viene mezclado en el precio, se grava. Es documentación, no precio."], "accent"),

  ("sec", "07", "CUÁNTO DEJA CADA CONTENEDOR"),
  ("table", ["PRECIO DE COMPRA", "PUESTO EN PUERTO", "UTILIDAD BRUTA", "%"], "lrrr",
    [["0.76 · apertura de negociación", "22,749", "13,483", "37%"],
     ["0.78 · base de este plan", "23,269", "12,963", "36%"],
     ["0.80", "23,788", "12,444", "34%"],
     ["0.8247 · cotización actual", "24,428", "11,804", "33%"],
     ["0.84 · referencia de mercado", "24,827", "11,405", "31%"]], {"hl": [1]}),
  ("p", "**El negocio funciona en todo el rango.** Entre el mejor y el peor precio la utilidad varía 15%, y el margen nunca baja de 31%. La negociación define cuánto se gana, no si se gana."),
  ("p", "Hoy el proveedor cotiza 0.8247. El objetivo es 0.78. Esa diferencia vale **27,816 al año**."),

  ("sec", "08", "CADENCIA Y CAPITAL"),
  ("p", "El ciclo de un contenedor es de 60 días: 30 de producción, 30 de tránsito. Se vende en 15 días."),
  ("call", None, ["**60 dividido entre 15 = 4 contenedores siempre en camino.**"], ""),
  ("table", ["CONTENEDOR", "SE PIDE", "LLEGA", "SE AGOTA"], "llll",
    [["1", "Día 0", "Día 60", "Día 75"],
     ["2", "Día 15", "Día 75", "Día 90"],
     ["3", "Día 30", "Día 90", "Día 105"],
     ["4", "Día 45", "Día 105", "Día 120"]], {}),
  ("call", "REGLA FIJA", ["Se pide cada 15 días, en calendario, sin esperar a que llegue el anterior. Esperar cuesta 60 días de inventario y quedarse sin producto se vuelve inevitable."], "accent"),
  ("h3", "Los 120,000"),
  ("table", ["DÍA", "APLICACIÓN", "USD", "ACUMULADO"], "llrr",
    [["0", "Anticipo 50% de 4 contenedores", "26,934", "26,934"],
     ["0", "Constitución y acuerdo operativo", "4,000", "30,934"],
     ["30", "Saldo contenedor 1", "6,734", "37,668"],
     ["45", "Saldo contenedor 2", "6,734", "44,402"],
     ["60", "Saldo contenedor 3 + aduana contenedor 1", "16,536", "60,938"],
     ["75", "Saldo contenedor 4", "6,734", "67,672"],
     ["90–105", "Aduana contenedores 2, 3 y 4", "29,406", "97,078"],
     ["—", "Reserva operativa", "22,922", "120,000"]], {"strong": [7]}),
  ("p", "**Por qué se pide capital si el negocio deja más de lo que se pide.** Porque el dinero sale dos meses antes de que entre. Hay que pagar cuatro contenedores completos antes de cobrar el primero."),
  ("p", "**Por qué el capital se queda.** No es un préstamo que se devuelve con la primera venta. Los cuatro contenedores en camino son inventario permanente: cuando uno se vende, otro ya está pagado y navegando. El capital es la base de trabajo del negocio y se recupera al liquidar, no al vender."),
  ("p", "**Y compra precio.** El proveedor da 0.78 solo contra pago anticipado del 50% o más. Con financiamiento parcial la estructura sería 30/70, que corresponde a 0.84. El capital no compra holgura: compra seis centavos por kilo."),
  ("p", "La reserva de 22,922 equivale a casi un contenedor completo. Absorbe un retraso de arribo, un ajuste de despacho o una variación de ciclo sin detener la cadencia de pedidos."),
  ("call", "CONTROL DEL CAPITAL", ["Los fondos aportados se mantienen en cuenta de custodia con un tercero independiente. Se liberan únicamente contra documentación de la operación: facturas de proveedor, flete, liquidación aduanal, servicios contratados. Cada movimiento se reporta a todos los participantes.", "No es un requisito externo. Es una decisión de la operación: el capital de un programa de importación se aplica a compromisos documentados, y un control de tercero lo hace verificable sin depender de la palabra de nadie."], ""),

  ("sec", "09", "RESULTADO ANUAL"),
  ("sub", "24 CONTENEDORES · 0.78 USD/KG"),
  ("table", ["CONCEPTO", "USD"], "lr",
    [["Venta bruta", "869,568"],
     ["Merma, devoluciones e incobrable (1%)", "–8,696"],
     ["Venta neta", "860,872"],
     ["Costo puesto en puerto", "–558,456"],
     ["Utilidad bruta · 35%", "302,416"],
     ["Arrastre de puerto a bodega", "–8,400"],
     ["Tecnología y gestión comercial", "–14,400"],
     ["Flota y entrega", "–10,800"],
     ["Administración (base + comisión)", "–56,400"],
     ["Aprendiz operativo", "–31,200"],
     ["Reserva arancelaria", "–8,157"],
     ["Contabilidad, legal, custodia y banca", "–9,000"],
     ["Antes de impuestos · 1.37x", "164,059"],
     ["Depreciación de vehículo y equipo", "–18,000"],
     ["Base gravable", "146,059"],
     ["Provisión fiscal estimada", "–38,000"],
     ["Después de impuestos · 1.05x", "126,059"]], {"strong": [2, 4, 12, 16]}),
  ("table", ["PRECIO DE COMPRA", "ANTES DE IMPUESTOS", "RETORNO"], "lrr",
    [["0.76", "176,539", "1.47x"],
     ["0.78", "164,059", "1.37x"],
     ["0.80", "151,603", "1.26x"],
     ["0.8247", "136,243", "1.14x"],
     ["0.84", "126,667", "1.06x"]], {"hl": [1]}),
  ("p", "En el peor escenario de precio, el negocio todavía cubre su capital dentro del primer año."),
  ("bar", "DÓNDE VA EL DINERO, EN SIMPLE",
    [("COMPRAR E IMPORTAR", 65), ("OPERAR", 16), ("IMPUESTOS", 4), ("QUEDA", 15)],
    "De cada 100 dólares vendidos, 65 se van en comprar e importar. 16 en operar — gente, entrega, tecnología, contabilidad. 4 en impuestos. Quedan 15."),
  ("note", "**Sobre los impuestos.** La provisión asume tributación a nivel de socio con elección de régimen S-corp, deducción de todos los gastos operativos, y depreciación de vehículo y equipo bajo Sección 179. Florida no aplica impuesto estatal sobre la renta personal. Cifra estimada; no constituye asesoría fiscal."),
  ("note", "**Sobre el impuesto de ventas.** El impuesto aplicable a la venta directa se factura al comprador por separado del precio y se remite al estado. No es ingreso del programa ni afecta el margen. Las ventas a distribuidores para reventa van amparadas por certificado de reventa y no causan impuesto en la transacción."),

  ("sec", "10", "CÓMO CRECE"),
  ("p", "Los 24 contenedores son el piso, no el techo. Tres vías abiertas, **ninguna proyectada en las cifras de este plan**:"),
  ("p", "**Despacho a mayoristas en otras ciudades.** Hay capacidad para 12 contenedores adicionales al año despachados fuera del radio de operación. No requiere bodega ni personal allá: solo despachar y cobrar."),
  ("p", "**Suministro bajo marca del comprador.** El mismo producto empacado bajo la marca de empresas distribuidoras. Usa la misma importación, la misma aduana y la misma logística de entrada, sin gasto comercial ni estructura adicional. Es una vía ya recorrida, y se abre naturalmente cuando la operación matriz demuestra constancia de suministro — que es la condición que este tipo de relación exige."),
  ("p", "**Mercado propio replicado.** Bodega, vehículo y dos personas en otra ciudad. Capital marginal de aproximadamente 95,000, menos que la primera unidad porque la estructura de importación ya existe."),
  ("call", "EL EFECTO QUE SE ACUMULA", ["Cada centavo por kilo negociado vale 6,240 al año por cada 24 contenedores. A mayor volumen, la posición frente al proveedor cambia de categoría: el precio de 0.76, hoy apertura de negociación, se vuelve precio de programa.", "**El volumen no solo suma venta. Baja el costo de todo lo que ya se compra.**"], ""),

  ("sec", "11", "CÓMO SE NEGOCIA CON EL PROVEEDOR"),
  ("table", ["PRECIO", "ESTRUCTURA DE PAGO QUE EXIGE"], "ll",
    [["0.84", "30% anticipo / 70% contra embarque"],
     ["0.80", "40 / 60"],
     ["0.78", "50 / 50 o más anticipado"]], {"hl": [2]}),
  ("p", "El descuento se paga con capital. Un proveedor que trabaja con 6% de margen no puede financiar al comprador."),
  ("p", "**Posición de apertura:** 24 contenedores al año, uno cada 15 días, anticipo sobre los cuatro primeros, 0.76 USD/kg con cláusula de ajuste por índice de materia prima. Cierre objetivo 0.78. Retiro en 0.82."),
  ("p", "24 contenedores son 415 toneladas anuales. Ese volumen justifica el precio y compra prioridad de línea de producción."),
  ("h3", "Cuatro términos que no se negocian"),
  ("terms", [
    ("1", "Peso neto por caja, tolerancia ±2%.", "Se compra por kilo y se vende por caja. Un faltante de peso no documentado es ingreso perdido que no aparece en ninguna factura."),
    ("2", "Especificación escrita con tolerancias.", "El acabado es lo primero que se recorta cuando el proveedor siente presión de costo."),
    ("3", "Inspección de tercero antes de cargar.", "300 a 400 dólares por contenedor. Se verifica peso y especificación antes de que zarpe."),
    ("4", "Cláusula de ajuste por materia prima, en ambos sentidos.", "Si el acero sube 15%, el costo del proveedor llega a 0.81 y el contrato se vuelve pérdida para él. Ahí es donde se detienen los embarques."),
  ]),

  ("sec", "12", "PREVISIONES Y RIESGOS"),
  ("p", "**Lo que está probado.** Un ciclo completo de importación, venta y cobro. El costo puesto en puerto, los márgenes y el tratamiento aduanal son cifras reales de esa operación."),
  ("p", "**Lo que es previsión.** Sostener la rotación de 15 días a lo largo de 24 contenedores al año, y el resultado proyectado sobre ese volumen. Los resultados reales diferirán."),
  ("risks", [
    ("Ritmo de venta", "Sostener la rotación a volumen anual depende de la capacidad de la operación directa.", "Es el destino del capital: trazabilidad por código de barras, gestión de cartera y equipo. El ritmo de compra funciona como amortiguador — si el inventario corre adelante se sostiene precio; si se acumula, se empuja volumen."),
    ("Arancel retroactivo", "El arancel se paga como depósito; la tasa final se fija después y se aplica hacia atrás, incluso sobre mercancía ya vendida.", "Reserva del 5% sobre los depósitos del año, constituida con utilidad y no con capital aportado. Se provisiona antes de cualquier reparto."),
    ("Un solo proveedor", "", "Dos canales de venta activos, ambos con cobro inmediato. Diversificar el origen de suministro es objetivo del segundo año."),
  ]),
  ("call", "ALCANCE", ["Todo aporte debe considerarse comprometido por el plazo completo del programa. Ninguna persona está autorizada a garantizar rendimiento. **Quien participe debe estar en posición de asumir la pérdida total del monto aportado.**"], "accent"),
  ("result", "RESULTADO ANUAL PROYECTADO", "USD 164,059",
    "antes de impuestos · 1.37x sobre capital solicitado",
    "USD 126,059 después de impuestos · 24 contenedores · ", "0.78 USD/kg FOB"),
]

META = {
  "running_left": "PRESSTON · LÍNEA REPLICABLE",
  "running_right": "PLAN OPERATIVO",
  "footer": "PRESSTON STRATEGIC PARTNERS LLC",
}
