# Plan operativo — ES.
# Narrativa, producto, costos y negociación: assets/plan-operativo-acero-es.pdf.
# Volumen, ciudades, resultados y retorno: el modelo de la calculadora del sitio
# (29 contenedores el año 1, 36 por ciudad en régimen, ciudad 2 en el año 2,
# ciudad 3 en el año 3; 1.01x / 1.28x / 1.77x / 5.49x; base USD 120,000).
# **texto** = negrita. Este archivo NUNCA se publica: construir.py lo cifra.

PLAN = [
  ("cover", {
    "brand": "PRESSTON STRATEGIC PARTNERS",
    "eyebrow": "PLAN OPERATIVO",
    "title": ["LÍNEA REPLICABLE", "DE IMPORTACIÓN", "Y DISTRIBUCIÓN"],
    "sub": "Tres ciudades en tres años · producto de ferretería",
    "figures": [
      ("Capital solicitado", "USD 120,000", None),
      ("Volumen", "29 contenedores el año 1", "36 por ciudad en régimen"),
      ("Ciudades", "Ciudad 2 en el año 2", "ciudad 3 en el año 3"),
      ("Distribuciones acumuladas", "1.01x · 1.28x", "1.77x al año 3"),
      ("Retorno total al año 3", "5.49x", "con la participación del 15%"),
      ("Plazo", "36 meses", "revisiones a los 12 y a los 24"),
    ],
    "foot": "DOCUMENTO CONFIDENCIAL · CÍRCULO PRIVADO DE SOCIOS",
  }),

  ("sec", "01", "QUÉ SE ESTÁ FINANCIANDO"),
  ("lead", "Esto no es un negocio de 29 contenedores. Es una línea de importación que se monta una vez y después se replica."),
  ("p", "Los 29 contenedores del primer año no son la meta. Son el arranque de una cadencia de 36 al año por ciudad, y sobre esa base está construido todo este plan."),
  ("p", "**Lo que cuesta montar la línea se paga una sola vez:** la relación con la fábrica, la fianza aduanera, el agente de aduana, el sistema de trazabilidad, la contabilidad y el cumplimiento. Esa estructura sirve igual para 36 contenedores que para 108."),
  ("p", "**Lo que se replica es barato:** espacio de bodega, un vehículo, dos personas."),
  ("p", "Por eso cada mercado nuevo cuesta menos que el anterior y rinde más: la ciudad 2 entra en el año 2 y la ciudad 3 en el año 3. Ahí está el negocio de largo plazo, no en el primer año."),
  ("call", "FUNCIÓN DE LA PRIMERA UNIDAD", ["Construir el historial de compra que desbloquea crédito del proveedor, probar la operación a volumen sostenido, y generar el flujo que financia la segunda y la tercera. **No hay una segunda solicitud de capital.**"], ""),

  ("sec", "02", "CÓMO SE GANA EL DINERO"),
  ("p", "Compramos de fábrica en origen, importamos por nuestro puerto de entrada, y vendemos."),
  ("unit", "POR CONTENEDOR", ["872 cajas", "Cuesta 23,269 puesto en puerto", "Se vende en 36,232"], "Deja 12,963"),
  ("p", "Ese ciclo ya se ejecutó completo: se compró, se importó, se despachó en aduana, se vendió y se cobró."),
  ("p", "**Vendemos un dólar por debajo del mercado y aun así ganamos 36% bruto.** Podemos hacerlo porque no cargamos las estructuras fijas de un distribuidor tradicional."),

  ("sec", "03", "EL PRODUCTO"),
  ("table", ["PRODUCTO", "CAJAS", "KG / CAJA", "PUESTO EN PUERTO", "PRECIO", "MARGEN"], "lrrrrr",
    [["Línea A", "480", "21.40", "28.84", "42.00", "31%"],
     ["Línea B", "196", "20.69", "27.88", "42.00", "34%"],
     ["Línea C", "196", "15.00", "20.22", "40.00", "49%"]], {}),
  ("caption", "Se compra por kilo y se vende por caja. El precio se negocia en un solo número: dólares por kilo FOB."),

  ("sec", "04", "DÓNDE SE VENDE"),
  ("p", "**Venta directa: 80% del volumen.** El cliente llega a la bodega y compra, o le llevamos el producto a la obra dentro de un radio de 60 millas. Se cobra al momento y queda el margen completo, sin comisión de nadie."),
  ("p", "**Mayoreo: 20% del volumen.** Se entrega producto a distribuidores con pago contra entrega. No hay crédito ni consignación: el cobro es inmediato, igual que en la venta directa. Rinde algo menos por caja, pero no depende de nuestra estructura operativa. Si la venta directa se interrumpe, este canal sigue moviendo producto."),
  ("table", ["CANAL", "%", "VENTA ANUAL POR CIUDAD"], "lrr",
    [["Directa", "80%", "1,043,482"],
     ["Mayoreo", "20%", "260,870"]], {"hl": [0]}),
  ("caption", "Mismo precio en los dos canales. Ciudad en régimen: 36 contenedores al año."),

  ("sec", "05", "POR QUÉ CUESTA MENOS OPERAR"),
  ("p", "**Bodega compartida.** No se paga renta de nave industrial. Se paga el espacio que se usa y crece con el volumen. Un distribuidor tradicional carga ese costo fijo desde el primer día, lo use o no."),
  ("p", "**Flota mixta.** Vehículo propio para la ruta base, contratistas por entrega en los picos. El costo de entrega sube y baja con el volumen en lugar de quedarse fijo. En un mes bajo no se paga flota parada."),
  ("p", "**Equipo formado adentro.** Se contrata gente joven que quiere aprender un oficio y se le forma en el ciclo completo: inventario, atención, entrega, y reparación y mecánica básica del producto. Cuesta menos que contratar perfiles hechos, y da personal que entiende el producto y resuelve en campo."),
  ("call", None, ["**Esto no es recorte. Es la estructura, y es lo que sostiene el precio.**"], ""),

  ("sec", "06", "QUÉ CUESTA TRAER UN CONTENEDOR"),
  ("sub", "A 0.78 USD/KG FOB"),
  ("table", ["CONCEPTO", "USD"], "lr",
    [["Mercancía", "13,467"],
     ["Arancel", "6,733"],
     ["Tasas aduanales", "64"],
     ["Flete marítimo", "2,600"],
     ["Despacho, agente, maniobras, seguro", "405"],
     ["Puesto en puerto", "23,269"]], {"strong": [5]}),
  ("p", "**El arancel pesa 2.6 veces más que el flete.** Por eso cada centavo negociado en el precio de compra vale más de lo que parece: se ahorra el centavo y también el arancel sobre ese centavo. Cada dólar recortado del FOB vale 1.50 en costo real."),
  ("p", "Negociar el precio de compra es la prioridad número uno, por encima de cualquier otro ahorro."),
  ("call", "VALE 1,244 POR CONTENEDOR SIN NEGOCIAR NADA", ["Si el flete marítimo viene identificado por separado en la factura, se deduce del valor aduanero y no paga arancel. Si viene mezclado en el precio, se grava. Es documentación, no precio."], "accent"),

  ("sec", "07", "CUÁNTO DEJA CADA CONTENEDOR"),
  ("table", ["PRECIO DE COMPRA", "PUESTO EN PUERTO", "UTILIDAD BRUTA", "%"], "lrrr",
    [["0.76 · apertura de negociación", "22,749", "13,483", "37%"],
     ["0.78 · base de este plan", "23,269", "12,963", "36%"],
     ["0.80", "23,788", "12,444", "34%"],
     ["0.8247 · cotización actual", "24,428", "11,804", "33%"],
     ["0.84 · referencia de mercado", "24,827", "11,405", "31%"]], {"hl": [1]}),
  ("p", "**El negocio funciona en todo el rango.** Entre el mejor y el peor precio la utilidad varía 15%, y el margen nunca baja de 31%. La negociación define cuánto se gana, no si se gana."),
  ("p", "Hoy el proveedor cotiza 0.8247. El objetivo es 0.78. Esa diferencia vale **41,724 al año por ciudad**."),

  ("sec", "08", "CADENCIA Y CAPITAL"),
  ("p", "El ciclo de un contenedor es de 60 días: 30 de producción, 30 de tránsito. El primero se vende en 15 días y, desde ahí, sale uno cada 10: tres al mes, 36 al año."),
  ("call", None, ["**60 dividido entre 10 = 6 contenedores siempre en camino.**"], ""),
  ("table", ["CONTENEDOR", "SE PIDE", "LLEGA", "SE AGOTA"], "llll",
    [["1", "Día 0", "Día 60", "Día 75"],
     ["2", "Día 10", "Día 70", "Día 85"],
     ["3", "Día 20", "Día 80", "Día 95"],
     ["4", "Día 30", "Día 90", "Día 105"],
     ["5", "Día 40", "Día 100", "Día 115"],
     ["6", "Día 50", "Día 110", "Día 125"]], {}),
  ("call", "REGLA FIJA", ["Se pide cada 10 días, en calendario, sin esperar a que llegue el anterior. Esperar cuesta 60 días de inventario y quedarse sin producto se vuelve inevitable."], "accent"),
  ("h3", "Los 120,000"),
  ("table", ["DÍA", "APLICACIÓN", "USD", "ACUMULADO"], "llrr",
    [["0", "Constitución y acuerdo operativo + anticipo 50% contenedor 1", "10,734", "10,734"],
     ["10", "Anticipo contenedor 2", "6,734", "17,468"],
     ["20", "Anticipo contenedor 3", "6,734", "24,202"],
     ["30", "Anticipo contenedor 4 + saldo contenedor 1", "13,467", "37,669"],
     ["40", "Anticipo contenedor 5 + saldo contenedor 2", "13,467", "51,136"],
     ["50", "Anticipo contenedor 6 + saldo contenedor 3", "13,467", "64,603"],
     ["60", "Anticipo contenedor 7 + saldo contenedor 4 + aduana y arrastre contenedor 1", "23,619", "88,222"],
     ["60–74", "Gastos operativos, desde la llegada de la mercancía", "5,513", "93,735"],
     ["70", "Anticipo contenedor 8 + saldo contenedor 5 + aduana y arrastre contenedor 2", "23,619", "117,354"],
     ["74", "Caja al punto de máxima exposición", "2,646", "120,000"]], {"strong": [9]}),
  ("p", "**Por qué se pide capital si el negocio deja más de lo que se pide.** Porque el dinero sale dos meses y medio antes de que entre. Antes de cobrar el primer contenedor ya se pagaron los anticipos de ocho, el saldo de cinco y la aduana de dos."),
  ("p", "**Por qué el capital se queda.** No es un préstamo que se devuelve con la primera venta. Los seis contenedores en camino son inventario permanente: cuando uno se vende, otro ya está pagado y navegando. El capital es la base de trabajo del negocio y se recupera con las distribuciones, no al vender."),
  ("p", "**Y compra precio.** El proveedor da 0.78 solo contra pago anticipado del 50% o más. Con financiamiento parcial la estructura sería 30/70, que corresponde a 0.84. El capital no compra holgura: compra seis centavos por kilo."),
  ("p", "El punto de máxima exposición es el día 74, un día antes de la primera venta. Desde el día 75 cada ciclo de 10 días deja **8,937 de caja**: la venta de un contenedor paga el anticipo del siguiente, el saldo del que embarca, la aduana del que llega y diez días de operación."),
  ("call", "CONTROL DEL CAPITAL", ["Los fondos aportados se mantienen en cuenta de custodia con un tercero independiente. Se liberan únicamente contra documentación de la operación: facturas de proveedor, flete, liquidación aduanal, servicios contratados. Cada movimiento se reporta a todos los participantes.", "No es un requisito externo. Es una decisión de la operación: el capital de un programa de importación se aplica a compromisos documentados, y un control de tercero lo hace verificable sin depender de la palabra de nadie."], ""),

  ("sec", "09", "RESULTADO ANUAL"),
  ("sub", "POR CIUDAD · 0.78 USD/KG"),
  ("table", ["CONCEPTO", "AÑO 1", "EN RÉGIMEN"], "lrr",
    [["Contenedores", "29", "36"],
     ["Venta", "1,050,728", "1,304,352"],
     ["Costo puesto en puerto", "–674,801", "–837,684"],
     ["Utilidad bruta", "375,927", "466,668"],
     ["Gastos operativos", "–111,798", "–134,157"],
     ["Contingencia 1%", "–3,759", "–4,667"],
     ["Antes de impuestos", "260,370", "327,844"],
     ["Margen neto", "24.8%", "25.1%"]], {"strong": [3, 6]}),
  ("caption", "El año 1 vende 29 contenedores porque los primeros 75 días son producción y tránsito."),
  ("h3", "Gastos operativos por ciudad"),
  ("table", ["CONCEPTO", "ANUAL", "MENSUAL"], "lrr",
    [["Administración (base + comisión)", "56,400", "4,700"],
     ["Aprendiz operativo", "31,200", "2,600"],
     ["Bodega compartida", "14,400", "1,200"],
     ["Tecnología y gestión comercial", "14,000", "1,167"],
     ["Flota y entrega", "10,000", "833"],
     ["Reserva arancelaria", "8,157", "680"],
     ["Total", "134,157", "11,180"]], {"strong": [6]}),
  ("p", "**Punto de equilibrio.** 11,180 de gasto mensual entre 12,963 de utilidad por contenedor da 0.86 contenedores al mes. Se venden tres."),
  ("table", ["PRECIO DE COMPRA", "ANTES DE IMPUESTOS, POR CIUDAD", "MARGEN NETO"], "lrr",
    [["0.76", "346,377", "26.6%"],
     ["0.78", "327,844", "25.1%"],
     ["0.80", "309,347", "23.7%"],
     ["0.8247", "286,538", "22.0%"],
     ["0.84", "272,317", "20.9%"]], {"hl": [1]}),
  ("p", "En el peor escenario de precio, el negocio todavía cubre su capital dentro del primer año."),
  ("bar", "DÓNDE VA EL DINERO, EN SIMPLE",
    [("COMPRAR E IMPORTAR", 64), ("OPERAR", 11), ("QUEDA", 25)],
    "De cada 100 dólares vendidos, 64 se van en comprar e importar y 11 en operar: gente, entrega, tecnología, administración. Quedan 25, antes de impuestos."),
  ("note", "**Sobre los impuestos.** Las cifras de este plan son antes de impuestos. Se asume tributación a nivel de socio con elección de régimen S-corp, deducción de todos los gastos operativos, y depreciación de vehículo y equipo bajo Sección 179. Florida no aplica impuesto estatal sobre la renta personal. No constituye asesoría fiscal."),
  ("note", "**Sobre el impuesto de ventas.** El impuesto aplicable a la venta directa se factura al comprador por separado del precio y se remite al estado. No es ingreso del programa ni afecta el margen. Las ventas a distribuidores para reventa van amparadas por certificado de reventa y no causan impuesto en la transacción."),

  ("sec", "10", "TRES CIUDADES EN TRES AÑOS"),
  ("p", "Cada ciudad nueva se abre con capital que ya generó la operación: **no hay segunda solicitud de capital**. Bodega, vehículo y dos personas. La importación, la aduana y la administración central ya existen, así que cada ciudad nueva carga 24,157 menos de estructura al año."),
  ("table", ["", "CIUDAD 2", "CIUDAD 3"], "lrr",
    [["Capital listo en caja", "Mes 15", "Mes 27"],
     ["Apertura", "Mes 18", "Mes 30"],
     ["Primera venta", "Mes 20", "Mes 32"],
     ["Capital del socio", "Ninguno", "Ninguno"]], {}),
  ("h3", "Proyección consolidada"),
  ("table", ["CONCEPTO", "AÑO 1", "AÑO 2", "AÑO 3", "RÉGIMEN"], "lrrrr",
    [["Ciudades", "1", "2", "3", "3"],
     ["Contenedores", "29", "50", "86", "108"],
     ["Venta", "1,050,728", "1,811,600", "3,115,952", "3,913,056"],
     ["Utilidad bruta", "375,927", "648,150", "1,114,818", "1,400,004"],
     ["Gastos operativos", "–111,798", "–179,990", "–289,990", "–354,157"],
     ["Contingencia 1%", "–3,759", "–6,482", "–11,148", "–14,000"],
     ["Antes de impuestos", "260,370", "461,678", "813,680", "1,031,847"]], {"strong": [6]}),
  ("p", "La ciudad 2 vende desde el mes 20 y la ciudad 3 desde el mes 32. Por eso el año 2 suma 14 contenedores de la segunda ciudad y el año 3, 14 de la tercera, sobre los 36 anuales de cada ciudad en marcha."),
  ("p", "Dos vías más quedan abiertas, **ninguna proyectada en estas cifras**:"),
  ("p", "**Despacho a mayoristas en otras ciudades.** Hay capacidad para 12 contenedores adicionales al año despachados fuera del radio de operación. No requiere bodega ni personal allá: solo despachar y cobrar."),
  ("p", "**Suministro bajo marca del comprador.** El mismo producto empacado bajo la marca de empresas distribuidoras. Usa la misma importación, la misma aduana y la misma logística de entrada, sin gasto comercial ni estructura adicional. Es una vía ya recorrida, y se abre naturalmente cuando la operación matriz demuestra constancia de suministro, que es la condición que este tipo de relación exige."),
  ("call", "EL EFECTO QUE SE ACUMULA", ["Cada centavo por kilo negociado vale 9,360 al año por cada ciudad de 36 contenedores. A mayor volumen, la posición frente al proveedor cambia de categoría: el precio de 0.76, hoy apertura de negociación, se vuelve precio de programa.", "**El volumen no solo suma venta. Baja el costo de todo lo que ya se compra.**"], ""),

  ("sec", "11", "LO QUE RECIBE EL SOCIO"),
  ("p", "Primero se repone el inventario y se pagan los gastos. Lo que queda es lo que se reparte: nunca se reparte sobre la venta bruta."),
  ("table", ["FASE", "DESTINO", "PARTE"], "llr",
    [["1 · hasta recuperar el capital", "Socio, recuperación preferente", "50%"],
     ["", "Capitalización de la empresa", "40%"],
     ["", "Administración", "10%"],
     ["2 · capital recuperado", "Socio, su participación del 15%", "15%"],
     ["", "Administración y crecimiento", "85%"]], {"hl": [0, 3]}),
  ("caption", "Fase 1: porcentaje de la utilidad neta. Fase 2: porcentaje de la caja distribuible."),
  ("table", ["CONCEPTO", "AÑO 1", "AÑO 2", "AÑO 3"], "lrrr",
    [["Distribución del año", "120,747", "33,241", "58,585"],
     ["Acumulado en efectivo", "120,747", "153,988", "212,573"],
     ["Múltiplo de las distribuciones", "1.01x", "1.28x", "1.77x"],
     ["Valor de la participación del 15%", "", "", "445,758"],
     ["Retorno total acumulado", "1.01x", "1.28x", "5.49x"]], {"strong": [4], "hl": [4]}),
  ("p", "**El capital se recupera en 12 meses** mediante las distribuciones de ganancias. Las ciudades 2 y 3 no piden capital al socio ni diluyen su participación: se financian con utilidad ya generada."),
  ("call", "PLAZO", ["36 meses, con revisiones a los 12 y a los 24."], "accent"),

  ("sec", "12", "CÓMO SE NEGOCIA CON EL PROVEEDOR"),
  ("table", ["PRECIO", "ESTRUCTURA DE PAGO QUE EXIGE"], "ll",
    [["0.84", "30% anticipo / 70% contra embarque"],
     ["0.80", "40 / 60"],
     ["0.78", "50 / 50 o más anticipado"]], {"hl": [2]}),
  ("p", "El descuento se paga con capital. Un proveedor que trabaja con 6% de margen no puede financiar al comprador."),
  ("p", "**Posición de apertura:** 36 contenedores al año por ciudad, uno cada 10 días, anticipo en cada pedido, 0.76 USD/kg con cláusula de ajuste por índice de materia prima. Cierre objetivo 0.78. Retiro en 0.82."),
  ("p", "36 contenedores son 622 toneladas anuales por ciudad. Ese volumen justifica el precio y compra prioridad de línea de producción."),
  ("h3", "Cuatro términos que no se negocian"),
  ("terms", [
    ("1", "Peso neto por caja, tolerancia ±2%.", "Se compra por kilo y se vende por caja. Un faltante de peso no documentado es ingreso perdido que no aparece en ninguna factura."),
    ("2", "Especificación escrita con tolerancias.", "El acabado es lo primero que se recorta cuando el proveedor siente presión de costo."),
    ("3", "Inspección de tercero antes de cargar.", "300 a 400 dólares por contenedor. Se verifica peso y especificación antes de que zarpe."),
    ("4", "Cláusula de ajuste por materia prima, en ambos sentidos.", "Si el acero sube 15%, el costo del proveedor llega a 0.81 y el contrato se vuelve pérdida para él. Ahí es donde se detienen los embarques."),
  ]),

  ("sec", "13", "PREVISIONES Y RIESGOS"),
  ("p", "**Lo que está probado.** Un ciclo completo de importación, venta y cobro. El costo puesto en puerto, los márgenes y el tratamiento aduanal son cifras reales de esa operación."),
  ("p", "**Lo que es previsión.** Sostener tres contenedores al mes por ciudad, abrir las ciudades 2 y 3 en los meses 18 y 30, y el resultado proyectado sobre ese volumen. Los resultados reales diferirán."),
  ("risks", [
    ("Ritmo de venta", "Sostener la rotación a volumen anual depende de la capacidad de la operación directa.", "Es el destino del capital: trazabilidad por código de barras, gestión de cartera y equipo. El ritmo de compra funciona como amortiguador: si el inventario corre adelante se sostiene precio; si se acumula, se empuja volumen."),
    ("Arancel retroactivo", "El arancel se paga como depósito; la tasa final se fija después y se aplica hacia atrás, incluso sobre mercancía ya vendida.", "Reserva arancelaria de 8,157 al año por ciudad, constituida con utilidad y no con capital aportado. Se provisiona antes de cualquier reparto."),
    ("Un solo proveedor", "", "Dos canales de venta activos, ambos con cobro inmediato. Diversificar el origen de suministro es objetivo del segundo año."),
  ]),
  ("call", "ALCANCE", ["Todo aporte debe considerarse comprometido por el plazo completo del programa. Ninguna persona está autorizada a garantizar rendimiento. **Quien participe debe estar en posición de asumir la pérdida total del monto aportado.**"], "accent"),
  ("result", "RETORNO TOTAL PROYECTADO A TRES AÑOS", "5.49x",
    "212,573 en distribuciones (1.77x) + 445,758 de valor de la participación del 15%",
    "Base USD 120,000 · 36 meses · ", "revisiones a los 12 y a los 24"),
]

META = {
  "running_left": "PRESSTON · LÍNEA REPLICABLE",
  "running_right": "PLAN OPERATIVO",
  "footer": "PRESSTON STRATEGIC PARTNERS LLC",
}
