# Operating plan — EN.
# Narrative, product, costs and negotiation: assets/plan-operativo-acero-en.pdf.
# Volume, cities, results and return: the site's calculator model (29 containers
# in year 1, 36 per city in steady state, city 2 in year 2, city 3 in year 3;
# 1.01x / 1.28x / 1.77x / 5.49x; USD 120,000 base).
# **text** = bold. NEVER published: construir.py encrypts it.

PLAN = [
  ("cover", {
    "brand": "PRESSTON STRATEGIC PARTNERS",
    "eyebrow": "OPERATING PLAN",
    "title": ["REPLICABLE LINE", "OF IMPORT", "AND DISTRIBUTION"],
    "sub": "Three cities in three years · hardware product",
    "figures": [
      ("Capital requested", "USD 120,000", None),
      ("Volume", "29 containers in year 1", "36 per city in steady state"),
      ("Cities", "City 2 in year 2", "city 3 in year 3"),
      ("Cumulative distributions", "1.01x · 1.28x", "1.77x by year 3"),
      ("Total return by year 3", "5.49x", "including the 15% stake"),
      ("Term", "36 months", "reviews at 12 and 24"),
    ],
    "foot": "CONFIDENTIAL DOCUMENT · PRIVATE CIRCLE OF MEMBERS",
  }),

  ("sec", "01", "WHAT IS BEING FINANCED"),
  ("lead", "This isn't a 29-container business. It's an import line that gets built once and is then replicated."),
  ("p", "The 29 containers in year one aren't the goal. They're the start of a cadence of 36 a year per city, and this entire plan is built on that base."),
  ("p", "**What it costs to set up the line is paid once:** the relationship with the factory, the customs bond, the customs broker, the traceability system, accounting, and compliance. That structure works the same for 36 containers as it does for 108."),
  ("p", "**What gets replicated is cheap:** warehouse space, one vehicle, two people."),
  ("p", "That's why every new market costs less than the last one and returns more: city 2 comes in during year 2 and city 3 during year 3. That's where the long-term business is, not in year one."),
  ("call", "FUNCTION OF THE FIRST UNIT", ["Build the purchase history that unlocks supplier credit, prove the operation at sustained volume, and generate the cash flow that finances the second and the third. **There is no second capital request.**"], ""),

  ("sec", "02", "HOW THE MONEY IS MADE"),
  ("p", "We buy from the factory at origin, import through our port of entry, and sell."),
  ("unit", "PER CONTAINER", ["872 boxes", "Costs 23,269 landed at port", "Sells for 36,232"], "Leaves 12,963"),
  ("p", "That cycle has already been executed in full: bought, imported, cleared through customs, sold, and collected."),
  ("p", "**We sell one dollar below market and still make 36% gross.** We can do that because we don't carry the fixed structures of a traditional distributor."),

  ("sec", "03", "THE PRODUCT"),
  ("table", ["PRODUCT", "BOXES", "KG / BOX", "LANDED AT PORT", "PRICE", "MARGIN"], "lrrrrr",
    [["Line A", "480", "21.40", "28.84", "42.00", "31%"],
     ["Line B", "196", "20.69", "27.88", "42.00", "34%"],
     ["Line C", "196", "15.00", "20.22", "40.00", "49%"]], {}),
  ("caption", "It's bought by the kilo and sold by the box. Price is negotiated in a single number: dollars per kilo FOB."),

  ("sec", "04", "WHERE IT SELLS"),
  ("p", "**Direct sale: 80% of volume.** The customer comes to the warehouse and buys, or we deliver to the job site within a 60-mile radius. Payment is collected on the spot and the full margin stays, with no commission to anyone."),
  ("p", "**Wholesale: 20% of volume.** Product is delivered to distributors on cash on delivery. No credit, no consignment: payment is immediate, just like direct sale. It yields somewhat less per box, but it doesn't depend on our operating structure. If direct sale is interrupted, this channel keeps moving product."),
  ("table", ["CHANNEL", "%", "ANNUAL SALES PER CITY"], "lrr",
    [["Direct", "80%", "1,043,482"],
     ["Wholesale", "20%", "260,870"]], {"hl": [0]}),
  ("caption", "Same price on both channels. City in steady state: 36 containers a year."),

  ("sec", "05", "WHY IT COSTS LESS TO OPERATE"),
  ("p", "**Shared warehouse.** No industrial lease is paid. You pay for the space you use, and it grows with volume. A traditional distributor carries that fixed cost from day one, whether they use it or not."),
  ("p", "**Mixed fleet.** Owned vehicle for the base route, contractors for delivery at peaks. Delivery cost rises and falls with volume instead of staying fixed. In a slow month, there's no idle fleet to pay for."),
  ("p", "**Team trained in-house.** We hire young people who want to learn a trade and train them across the full cycle: inventory, customer service, delivery, and basic repair and mechanics of the product. It costs less than hiring finished profiles, and it produces staff who understand the product and solve problems in the field."),
  ("call", None, ["**This isn't cost-cutting. It's the structure, and it's what holds up the price.**"], ""),

  ("sec", "06", "WHAT IT COSTS TO BRING IN A CONTAINER"),
  ("sub", "AT 0.78 USD/KG FOB"),
  ("table", ["ITEM", "USD"], "lr",
    [["Merchandise", "13,467"],
     ["Duty", "6,733"],
     ["Customs fees", "64"],
     ["Ocean freight", "2,600"],
     ["Clearance, broker, handling, insurance", "405"],
     ["Landed at port", "23,269"]], {"strong": [5]}),
  ("p", "**Duty weighs 2.6 times more than freight.** That's why every cent negotiated on the purchase price is worth more than it looks: you save the cent, and also the duty on that cent. Every dollar cut from FOB is worth 1.50 in real cost."),
  ("p", "Negotiating the purchase price is priority number one, above any other saving."),
  ("call", "WORTH 1,244 PER CONTAINER WITHOUT NEGOTIATING ANYTHING", ["If ocean freight is itemized separately on the invoice, it's deducted from the customs value and doesn't pay duty. If it's mixed into the price, it's taxed. It's documentation, not price."], "accent"),

  ("sec", "07", "WHAT EACH CONTAINER LEAVES"),
  ("table", ["PURCHASE PRICE", "LANDED AT PORT", "GROSS PROFIT", "%"], "lrrr",
    [["0.76 · opening negotiation", "22,749", "13,483", "37%"],
     ["0.78 · this plan's base", "23,269", "12,963", "36%"],
     ["0.80", "23,788", "12,444", "34%"],
     ["0.8247 · current quote", "24,428", "11,804", "33%"],
     ["0.84 · market reference", "24,827", "11,405", "31%"]], {"hl": [1]}),
  ("p", "**The business works across the whole range.** Between the best and worst price, profit varies by 15%, and margin never drops below 31%. Negotiation decides how much you make, not whether you make it."),
  ("p", "Today the supplier is quoting 0.8247. The target is 0.78. That difference is worth **41,724 a year per city**."),

  ("sec", "08", "CADENCE AND CAPITAL"),
  ("p", "A container's cycle is 60 days: 30 days of production, 30 days in transit. The first one sells in 15 days and, from then on, one goes out every 10: three a month, 36 a year."),
  ("call", None, ["**60 divided by 10 = 6 containers always on the way.**"], ""),
  ("table", ["CONTAINER", "ORDERED", "ARRIVES", "SOLD OUT"], "llll",
    [["1", "Day 0", "Day 60", "Day 75"],
     ["2", "Day 10", "Day 70", "Day 85"],
     ["3", "Day 20", "Day 80", "Day 95"],
     ["4", "Day 30", "Day 90", "Day 105"],
     ["5", "Day 40", "Day 100", "Day 115"],
     ["6", "Day 50", "Day 110", "Day 125"]], {}),
  ("call", "FIXED RULE", ["Orders go out every 10 days, on schedule, without waiting for the previous one to arrive. Waiting costs 60 days of inventory, and running out of product becomes inevitable."], "accent"),
  ("h3", "The 120,000"),
  ("table", ["DAY", "APPLICATION", "USD", "CUMULATIVE"], "llrr",
    [["0", "Formation and operating agreement + 50% deposit, container 1", "10,734", "10,734"],
     ["10", "Deposit, container 2", "6,734", "17,468"],
     ["20", "Deposit, container 3", "6,734", "24,202"],
     ["30", "Deposit, container 4 + balance, container 1", "13,467", "37,669"],
     ["40", "Deposit, container 5 + balance, container 2", "13,467", "51,136"],
     ["50", "Deposit, container 6 + balance, container 3", "13,467", "64,603"],
     ["60", "Deposit, container 7 + balance, container 4 + customs and drayage, container 1", "23,619", "88,222"],
     ["60–74", "Operating expenses, from the arrival of merchandise", "5,513", "93,735"],
     ["70", "Deposit, container 8 + balance, container 5 + customs and drayage, container 2", "23,619", "117,354"],
     ["74", "Cash at the point of peak exposure", "2,646", "120,000"]], {"strong": [9]}),
  ("p", "**Why capital is requested if the business leaves more than it asks for.** Because the money goes out two and a half months before it comes in. Before the first container is collected on, the deposits on eight, the balance on five, and the customs on two have already been paid."),
  ("p", "**Why the capital stays put.** It's not a loan that gets repaid with the first sale. The six containers on the way are permanent inventory: when one sells, another is already paid for and sailing. The capital is the working base of the business, and it's recovered through distributions, not on each sale."),
  ("p", "**And it buys price.** The supplier gives 0.78 only against an advance payment of 50% or more. With partial financing the structure would be 30/70, which corresponds to 0.84. Capital doesn't buy slack: it buys six cents per kilo."),
  ("p", "Peak exposure is day 74, one day before the first sale. From day 75, every 10-day cycle leaves **8,937 in cash**: the sale of one container pays the next one's deposit, the balance of the one shipping, the customs of the one arriving, and ten days of operation."),
  ("call", "CONTROL OF CAPITAL", ["Contributed funds are held in a custody account with an independent third party. They're released only against documentation of the operation: supplier invoices, freight, customs settlement, contracted services. Every movement is reported to all participants.", "This isn't an external requirement. It's an operating decision: capital in an import program is applied to documented commitments, and third-party control makes it verifiable without depending on anyone's word."], ""),

  ("sec", "09", "ANNUAL RESULT"),
  ("sub", "PER CITY · 0.78 USD/KG"),
  ("table", ["ITEM", "YEAR 1", "STEADY STATE"], "lrr",
    [["Containers", "29", "36"],
     ["Sales", "1,050,728", "1,304,352"],
     ["Cost landed at port", "–674,801", "–837,684"],
     ["Gross profit", "375,927", "466,668"],
     ["Operating expenses", "–111,798", "–134,157"],
     ["Contingency 1%", "–3,759", "–4,667"],
     ["Before taxes", "260,370", "327,844"],
     ["Net margin", "24.8%", "25.1%"]], {"strong": [3, 6]}),
  ("caption", "Year 1 sells 29 containers because the first 75 days are production and transit."),
  ("h3", "Operating expenses per city"),
  ("table", ["ITEM", "ANNUAL", "MONTHLY"], "lrr",
    [["Administration (base + commission)", "56,400", "4,700"],
     ["Trainee operator", "31,200", "2,600"],
     ["Shared warehouse", "14,400", "1,200"],
     ["Technology and sales management", "14,000", "1,167"],
     ["Fleet and delivery", "10,000", "833"],
     ["Tariff reserve", "8,157", "680"],
     ["Total", "134,157", "11,180"]], {"strong": [6]}),
  ("p", "**Break-even.** 11,180 in monthly expense divided by 12,963 of profit per container gives 0.86 containers a month. We sell three."),
  ("table", ["PURCHASE PRICE", "BEFORE TAXES, PER CITY", "NET MARGIN"], "lrr",
    [["0.76", "346,377", "26.6%"],
     ["0.78", "327,844", "25.1%"],
     ["0.80", "309,347", "23.7%"],
     ["0.8247", "286,538", "22.0%"],
     ["0.84", "272,317", "20.9%"]], {"hl": [1]}),
  ("p", "In the worst-case pricing scenario, the business still covers its capital within the first year."),
  ("bar", "WHERE THE MONEY GOES, SIMPLY PUT",
    [("BUY AND IMPORT", 64), ("OPERATE", 11), ("LEFT OVER", 25)],
    "Of every 100 dollars sold, 64 go to buying and importing and 11 to operating: people, delivery, technology, administration. 25 are left over, before taxes."),
  ("note", "**On taxes.** The figures in this plan are before taxes. They assume member-level taxation with an S-corp election, deduction of all operating expenses, and vehicle and equipment depreciation under Section 179. Florida applies no state tax on personal income. Not tax advice."),
  ("note", "**On sales tax.** Sales tax applicable to direct sale is billed to the buyer separately from the price and remitted to the state. It is not program income and does not affect margin. Sales to distributors for resale are covered by a resale certificate and do not trigger tax on the transaction."),

  ("sec", "10", "THREE CITIES IN THREE YEARS"),
  ("p", "Each new city opens with capital the operation has already generated: **there is no second capital request**. Warehouse, vehicle, and two people. Import, customs, and central administration already exist, so each new city carries 24,157 less in structure a year."),
  ("table", ["", "CITY 2", "CITY 3"], "lrr",
    [["Capital ready in cash", "Month 15", "Month 27"],
     ["Opening", "Month 18", "Month 30"],
     ["First sale", "Month 20", "Month 32"],
     ["Capital from the partner", "None", "None"]], {}),
  ("h3", "Consolidated projection"),
  ("table", ["ITEM", "YEAR 1", "YEAR 2", "YEAR 3", "STEADY"], "lrrrr",
    [["Cities", "1", "2", "3", "3"],
     ["Containers", "29", "50", "86", "108"],
     ["Sales", "1,050,728", "1,811,600", "3,115,952", "3,913,056"],
     ["Gross profit", "375,927", "648,150", "1,114,818", "1,400,004"],
     ["Operating expenses", "–111,798", "–179,990", "–289,990", "–354,157"],
     ["Contingency 1%", "–3,759", "–6,482", "–11,148", "–14,000"],
     ["Before taxes", "260,370", "461,678", "813,680", "1,031,847"]], {"strong": [6]}),
  ("p", "City 2 sells from month 20 and city 3 from month 32. That's why year 2 adds 14 containers from the second city and year 3 adds 14 from the third, on top of the 36 a year each running city already produces."),
  ("p", "Two more paths stay open, **neither projected in these figures**:"),
  ("p", "**Dispatch to wholesalers in other cities.** There's capacity for 12 additional containers a year dispatched outside the operating radius. It requires no warehouse or staff there: just dispatch and collect."),
  ("p", "**Supply under the buyer's own brand.** The same product packaged under the brand of distributor companies. It uses the same import, the same customs, and the same inbound logistics, with no sales cost or added structure. It's a path already traveled, and it opens naturally once the parent operation demonstrates consistency of supply, which is the condition this kind of relationship requires."),
  ("call", "THE COMPOUNDING EFFECT", ["Every cent per kilo negotiated is worth 9,360 a year for each city of 36 containers. At higher volume, the position with the supplier changes category: the price of 0.76, today an opening negotiation, becomes the program price.", "**Volume doesn't just add sales. It lowers the cost of everything already being bought.**"], ""),

  ("sec", "11", "WHAT THE PARTNER RECEIVES"),
  ("p", "Inventory is replenished and expenses are paid first. What is left is what gets distributed: distributions are never made against gross sales."),
  ("table", ["PHASE", "DESTINATION", "SHARE"], "llr",
    [["1 · until capital is recovered", "Partner, preferential recovery", "50%"],
     ["", "Company capitalization", "40%"],
     ["", "Administration", "10%"],
     ["2 · capital recovered", "Partner, their 15% stake", "15%"],
     ["", "Administration and growth", "85%"]], {"hl": [0, 3]}),
  ("caption", "Phase 1: share of net profit. Phase 2: share of distributable cash."),
  ("table", ["ITEM", "YEAR 1", "YEAR 2", "YEAR 3"], "lrrr",
    [["Distribution for the year", "120,747", "33,241", "58,585"],
     ["Cash accumulated", "120,747", "153,988", "212,573"],
     ["Distribution multiple", "1.01x", "1.28x", "1.77x"],
     ["Value of the 15% stake", "", "", "445,758"],
     ["Cumulative total return", "1.01x", "1.28x", "5.49x"]], {"strong": [4], "hl": [4]}),
  ("p", "USD 120,000 for 15% reflects the infrastructure, know-how, and scaffolding already built (a USD 800,000 valuation): that is why the return is 5.49x, not the 5.64x of a mechanical calculation."),
  ("p", "The capital is almost all inventory: tangible merchandise in motion. The operating reserve (22,922) is what keeps the company running."),
  ("p", "**Capital is recovered in 12 months** through profit distributions. Cities 2 and 3 ask the partner for no capital and don't dilute their stake: they're funded with profit already generated."),
  ("call", "TERM", ["36 months, with reviews at 12 and 24."], "accent"),

  ("sec", "12", "HOW THE SUPPLIER IS NEGOTIATED WITH"),
  ("table", ["PRICE", "PAYMENT STRUCTURE IT REQUIRES"], "ll",
    [["0.84", "30% deposit / 70% against shipment"],
     ["0.80", "40 / 60"],
     ["0.78", "50 / 50 or more upfront"]], {"hl": [2]}),
  ("p", "The discount is paid for with capital. A supplier working on a 6% margin can't finance the buyer."),
  ("p", "**Opening position:** 36 containers a year per city, one every 10 days, a deposit on each order, 0.76 USD/kg with a raw-material index adjustment clause. Target close 0.78. Walk-away at 0.82."),
  ("p", "36 containers are 622 tons a year per city. That volume justifies the price and buys priority on the production line."),
  ("h3", "Four terms that don't get negotiated"),
  ("terms", [
    ("1", "Net weight per box, ±2% tolerance.", "It's bought by the kilo and sold by the box. An undocumented weight shortfall is lost income that shows up on no invoice."),
    ("2", "Written specification with tolerances.", "Finish is the first thing that gets cut when the supplier feels cost pressure."),
    ("3", "Third-party inspection before loading.", "300 to 400 dollars per container. Weight and specification are verified before it sails."),
    ("4", "Raw-material adjustment clause, in both directions.", "If steel rises 15%, the supplier's cost reaches 0.81 and the contract becomes a loss for them. That's where shipments stop."),
  ]),

  ("sec", "13", "FORECASTS AND RISKS"),
  ("p", "**What's proven.** A full cycle of import, sale, and collection. The cost landed at port, the margins, and the customs treatment are real figures from that operation."),
  ("p", "**What's forecast.** Sustaining three containers a month per city, opening cities 2 and 3 in months 18 and 30, and the result projected on that volume. Actual results will differ."),
  ("risks", [
    ("Sales pace", "Sustaining annual-volume rotation depends on the capacity of direct operations.", "It's where the capital goes: barcode traceability, portfolio management, and staff. The buying pace acts as a buffer: if inventory runs ahead, price holds; if it builds up, volume is pushed."),
    ("Retroactive duty", "Duty is paid as a deposit; the final rate is set later and applied retroactively, even on merchandise already sold.", "A tariff reserve of 8,157 a year per city, built from profit and not from contributed capital. It's provisioned before any distribution."),
    ("Single supplier", "", "Two active sales channels, both with immediate collection. Diversifying the supply origin is a second-year objective."),
  ]),
  ("call", "SCOPE", ["Every contribution should be considered committed for the program's full term. No one is authorized to guarantee a return. **Whoever participates must be in a position to accept the total loss of the amount contributed.**"], "accent"),
  ("result", "PROJECTED TOTAL RETURN AT THREE YEARS", "5.49x",
    "212,573 in distributions (1.77x) + 445,758 in value of the 15% stake",
    "USD 120,000 base · 36 months · ", "reviews at 12 and 24"),
]

META = {
  "running_left": "PRESSTON · REPLICABLE LINE",
  "running_right": "OPERATING PLAN",
  "footer": "PRESSTON STRATEGIC PARTNERS LLC",
}
