# Operating plan — EN. Copied verbatim from assets/plan-operativo-acero-en.pdf.
# **text** = bold in the original. NEVER published: construir.py renders and encrypts it.

PLAN = [
  ("cover", {
    "brand": "PRESSTON STRATEGIC PARTNERS",
    "eyebrow": "OPERATING PLAN",
    "title": ["REPLICABLE LINE", "OF IMPORT", "AND DISTRIBUTION"],
    "sub": "First unit · hardware product",
    "figures": [
      ("Capital requested", "USD 120,000", None),
      ("Base volume", "24 containers per year", None),
      ("Projected gross profit", "USD 302,416", "35%"),
      ("Result before taxes", "USD 164,059", "1.37x"),
      ("Result after taxes", "USD 126,059", "1.05x"),
    ],
    "foot": "CONFIDENTIAL DOCUMENT · PRIVATE CIRCLE OF MEMBERS",
  }),

  ("sec", "01", "WHAT IS BEING FINANCED"),
  ("lead", "This isn't a 24-container business. It's an import line that gets built once and is then replicated."),
  ("p", "The 24 containers in year one aren't the goal. They're the minimum volume we already know how to place, and this entire plan is built on that base. It's projected on that number because it's the only one that's proven, not because it's the ceiling."),
  ("p", "**What it costs to set up the line is paid once:** the relationship with the factory, the customs bond, the customs broker, the traceability system, accounting, and compliance. That structure works the same for 24 containers as it does for 100."),
  ("p", "**What gets replicated is cheap:** warehouse space, one vehicle, two people."),
  ("p", "That's why every new market costs less than the last one and returns more. That's where the long-term business is, not in year one."),
  ("call", "FUNCTION OF THE FIRST UNIT", ["Build the purchase history that unlocks supplier credit, prove the operation at sustained volume, and generate the cash flow that finances the second one. **There is no second capital request.**"], ""),

  ("sec", "02", "HOW THE MONEY IS MADE"),
  ("p", "We buy from the factory at origin, import through our port of entry, and sell."),
  ("unit", "PER CONTAINER", ["872 boxes", "Costs 23,269 landed at port", "Sells for 36,232"], "Leaves 12,963"),
  ("p", "That cycle has already been executed in full: bought, imported, cleared through customs, sold, and collected."),
  ("p", "**We sell one dollar below market and still make 35% gross.** We can do that because we don't carry the fixed structures of a traditional distributor."),

  ("sec", "03", "THE PRODUCT"),
  ("table", ["PRODUCT", "BOXES", "KG / BOX", "LANDED AT PORT", "PRICE", "MARGIN"], "lrrrrr",
    [["Line A", "480", "21.40", "28.84", "42.00", "31%"],
     ["Line B", "196", "20.69", "27.88", "42.00", "34%"],
     ["Line C", "196", "15.00", "20.22", "40.00", "49%"]], {}),
  ("caption", "It's bought by the kilo and sold by the box. Price is negotiated in a single number: dollars per kilo FOB."),

  ("sec", "04", "WHERE IT SELLS"),
  ("p", "**Direct sale — 80% of volume.** The customer comes to the warehouse and buys, or we deliver to the job site within a 60-mile radius. Payment is collected on the spot and the full margin stays, with no commission to anyone."),
  ("p", "**Wholesale — 20% of volume.** Product is delivered to distributors on cash on delivery. No credit, no consignment: payment is immediate, just like direct sale. It yields somewhat less per box, but it doesn't depend on our operating structure — if direct sale is interrupted, this channel keeps moving product."),
  ("table", ["CHANNEL", "%", "ANNUAL SALES"], "lrr",
    [["Direct", "80%", "695,654"],
     ["Wholesale", "20%", "173,914"]], {"hl": [0]}),
  ("caption", "Same price on both channels."),

  ("sec", "05", "WHY IT COSTS LESS TO OPERATE"),
  ("p", "**Shared warehouse.** No industrial lease is paid. You pay for the space you use, and it grows with volume. A traditional distributor carries that fixed cost from day one, whether they use it or not."),
  ("p", "**Mixed fleet.** Owned vehicle for the base route, contractors for delivery at peaks. Delivery cost rises and falls with volume instead of staying fixed. In a slow month, there's no idle fleet to pay for."),
  ("p", "**Team trained in-house.** We hire young people who want to learn a trade and train them across the full cycle: inventory, customer service, delivery, and basic repair and mechanics of the product. It costs less than hiring finished profiles, and it produces staff who understand the product and solve problems in the field."),
  ("call", None, ["**This isn't cost-cutting. It's the structure, and it's what holds up the price.**"], ""),

  ("sec", "06", "WHAT IT COSTS TO BRING IN A CONTAINER"),
  ("sub", "AT 0.78 USD/KG FOB"),
  ("table", ["ITEM", "USD"], "lr",
    [["Merchandise", "13,467"],
     ["Duty", "6,733"],
     ["Customs fees", "64"],
     ["Ocean freight", "2,600"],
     ["Clearance, broker, handling, insurance", "405"],
     ["Landed at port", "23,269"]], {"strong": [5]}),
  ("p", "**Duty weighs 2.6 times more than freight.** That's why every cent negotiated on the purchase price is worth more than it looks: you save the cent, and also the duty on that cent. Every dollar cut from FOB is worth 1.50 in real cost."),
  ("p", "Negotiating the purchase price is priority number one, above any other saving."),
  ("call", "WORTH 1,244 PER CONTAINER WITHOUT NEGOTIATING ANYTHING", ["If ocean freight is itemized separately on the invoice, it's deducted from the customs value and doesn't pay duty. If it's mixed into the price, it's taxed. It's documentation, not price."], "accent"),

  ("sec", "07", "WHAT EACH CONTAINER LEAVES"),
  ("table", ["PURCHASE PRICE", "LANDED AT PORT", "GROSS PROFIT", "%"], "lrrr",
    [["0.76 · opening negotiation", "22,749", "13,483", "37%"],
     ["0.78 · this plan's base", "23,269", "12,963", "36%"],
     ["0.80", "23,788", "12,444", "34%"],
     ["0.8247 · current quote", "24,428", "11,804", "33%"],
     ["0.84 · market reference", "24,827", "11,405", "31%"]], {"hl": [1]}),
  ("p", "**The business works across the whole range.** Between the best and worst price, profit varies by 15%, and margin never drops below 31%. Negotiation decides how much you make, not whether you make it."),
  ("p", "Today the supplier is quoting 0.8247. The target is 0.78. That difference is worth **27,816 a year**."),

  ("sec", "08", "CADENCE AND CAPITAL"),
  ("p", "A container's cycle is 60 days: 30 days of production, 30 days in transit. It sells in 15 days."),
  ("call", None, ["**60 divided by 15 = 4 containers always on the way.**"], ""),
  ("table", ["CONTAINER", "ORDERED", "ARRIVES", "SOLD OUT"], "llll",
    [["1", "Day 0", "Day 60", "Day 75"],
     ["2", "Day 15", "Day 75", "Day 90"],
     ["3", "Day 30", "Day 90", "Day 105"],
     ["4", "Day 45", "Day 105", "Day 120"]], {}),
  ("call", "FIXED RULE", ["Orders go out every 15 days, on schedule, without waiting for the previous one to arrive. Waiting costs 60 days of inventory, and running out of product becomes inevitable."], "accent"),
  ("h3", "The 120,000"),
  ("table", ["DAY", "APPLICATION", "USD", "CUMULATIVE"], "llrr",
    [["0", "50% deposit on 4 containers", "26,934", "26,934"],
     ["0", "Formation and operating agreement", "4,000", "30,934"],
     ["30", "Balance, container 1", "6,734", "37,668"],
     ["45", "Balance, container 2", "6,734", "44,402"],
     ["60", "Balance, container 3 + customs, container 1", "16,536", "60,938"],
     ["75", "Balance, container 4", "6,734", "67,672"],
     ["90–105", "Customs, containers 2, 3 and 4", "29,406", "97,078"],
     ["—", "Operating reserve", "22,922", "120,000"]], {"strong": [7]}),
  ("p", "**Why capital is requested if the business leaves more than it asks for.** Because the money goes out two months before it comes in. Four full containers have to be paid before the first one is collected on."),
  ("p", "**Why the capital stays put.** It's not a loan that gets repaid with the first sale. The four containers on the way are permanent inventory: when one sells, another is already paid for and sailing. The capital is the working base of the business, and it's recovered on wind-down, not on each sale."),
  ("p", "**And it buys price.** The supplier gives 0.78 only against an advance payment of 50% or more. With partial financing the structure would be 30/70, which corresponds to 0.84. Capital doesn't buy slack: it buys six cents per kilo."),
  ("p", "The 22,922 reserve is equivalent to almost a full container. It absorbs a shipping delay, a clearance adjustment, or a cycle variation without stopping the ordering cadence."),
  ("call", "CONTROL OF CAPITAL", ["Contributed funds are held in a custody account with an independent third party. They're released only against documentation of the operation: supplier invoices, freight, customs settlement, contracted services. Every movement is reported to all participants.", "This isn't an external requirement. It's an operating decision: capital in an import program is applied to documented commitments, and third-party control makes it verifiable without depending on anyone's word."], ""),

  ("sec", "09", "ANNUAL RESULT"),
  ("sub", "24 CONTAINERS · 0.78 USD/KG"),
  ("table", ["ITEM", "USD"], "lr",
    [["Gross sales", "869,568"],
     ["Shrinkage, returns and bad debt (1%)", "–8,696"],
     ["Net sales", "860,872"],
     ["Cost landed at port", "–558,456"],
     ["Gross profit · 35%", "302,416"],
     ["Port-to-warehouse drayage", "–8,400"],
     ["Technology and sales management", "–14,400"],
     ["Fleet and delivery", "–10,800"],
     ["Administration (base + commission)", "–56,400"],
     ["Trainee operator", "–31,200"],
     ["Tariff reserve", "–8,157"],
     ["Accounting, legal, custody and banking", "–9,000"],
     ["Before taxes · 1.37x", "164,059"],
     ["Vehicle and equipment depreciation", "–18,000"],
     ["Taxable base", "146,059"],
     ["Estimated tax provision", "–38,000"],
     ["After taxes · 1.05x", "126,059"]], {"strong": [2, 4, 12, 16]}),
  ("table", ["PURCHASE PRICE", "BEFORE TAXES", "RETURN"], "lrr",
    [["0.76", "176,539", "1.47x"],
     ["0.78", "164,059", "1.37x"],
     ["0.80", "151,603", "1.26x"],
     ["0.8247", "136,243", "1.14x"],
     ["0.84", "126,667", "1.06x"]], {"hl": [1]}),
  ("p", "In the worst-case pricing scenario, the business still covers its capital within the first year."),
  ("bar", "WHERE THE MONEY GOES, SIMPLY PUT",
    [("BUY AND IMPORT", 65), ("OPERATE", 16), ("TAXES", 4), ("LEFT OVER", 15)],
    "Of every 100 dollars sold, 65 go to buying and importing. 16 to operating — people, delivery, technology, accounting. 4 to taxes. 15 are left over."),
  ("note", "**On taxes.** The provision assumes member-level taxation with an S-corp election, deduction of all operating expenses, and vehicle and equipment depreciation under Section 179. Florida applies no state tax on personal income. Estimated figure; not tax advice."),
  ("note", "**On sales tax.** Sales tax applicable to direct sale is billed to the buyer separately from the price and remitted to the state. It is not program income and does not affect margin. Sales to distributors for resale are covered by a resale certificate and do not trigger tax on the transaction."),

  ("sec", "10", "HOW IT GROWS"),
  ("p", "The 24 containers are the floor, not the ceiling. Three open paths, **none projected in this plan's figures**:"),
  ("p", "**Dispatch to wholesalers in other cities.** There's capacity for 12 additional containers a year dispatched outside the operating radius. It requires no warehouse or staff there: just dispatch and collect."),
  ("p", "**Supply under the buyer's own brand.** The same product packaged under the brand of distributor companies. It uses the same import, the same customs, and the same inbound logistics, with no sales cost or added structure. It's a path already traveled, and it opens naturally once the parent operation demonstrates consistency of supply — which is the condition this kind of relationship requires."),
  ("p", "**Own market, replicated.** Warehouse, vehicle, and two people in another city. Marginal capital of approximately 95,000, less than the first unit because the import structure already exists."),
  ("call", "THE COMPOUNDING EFFECT", ["Every cent per kilo negotiated is worth 6,240 a year for every 24 containers. At higher volume, the position with the supplier changes category: the price of 0.76, today an opening negotiation, becomes the program price.", "**Volume doesn't just add sales. It lowers the cost of everything already being bought.**"], ""),

  ("sec", "11", "HOW THE SUPPLIER IS NEGOTIATED WITH"),
  ("table", ["PRICE", "PAYMENT STRUCTURE IT REQUIRES"], "ll",
    [["0.84", "30% deposit / 70% against shipment"],
     ["0.80", "40 / 60"],
     ["0.78", "50 / 50 or more upfront"]], {"hl": [2]}),
  ("p", "The discount is paid for with capital. A supplier working on a 6% margin can't finance the buyer."),
  ("p", "**Opening position:** 24 containers a year, one every 15 days, deposit on the first four, 0.76 USD/kg with a raw-material index adjustment clause. Target close 0.78. Walk-away at 0.82."),
  ("p", "24 containers are 415 tons a year. That volume justifies the price and buys priority on the production line."),
  ("h3", "Four terms that don't get negotiated"),
  ("terms", [
    ("1", "Net weight per box, ±2% tolerance.", "It's bought by the kilo and sold by the box. An undocumented weight shortfall is lost income that shows up on no invoice."),
    ("2", "Written specification with tolerances.", "Finish is the first thing that gets cut when the supplier feels cost pressure."),
    ("3", "Third-party inspection before loading.", "300 to 400 dollars per container. Weight and specification are verified before it sails."),
    ("4", "Raw-material adjustment clause, in both directions.", "If steel rises 15%, the supplier's cost reaches 0.81 and the contract becomes a loss for them. That's where shipments stop."),
  ]),

  ("sec", "12", "FORECASTS AND RISKS"),
  ("p", "**What's proven.** A full cycle of import, sale, and collection. The cost landed at port, the margins, and the customs treatment are real figures from that operation."),
  ("p", "**What's forecast.** Sustaining the 15-day rotation across 24 containers a year, and the result projected on that volume. Actual results will differ."),
  ("risks", [
    ("Sales pace", "Sustaining annual-volume rotation depends on the capacity of direct operations.", "It's where the capital goes: barcode traceability, portfolio management, and staff. The buying pace acts as a buffer — if inventory runs ahead, price holds; if it builds up, volume is pushed."),
    ("Retroactive duty", "Duty is paid as a deposit; the final rate is set later and applied retroactively, even on merchandise already sold.", "A 5% reserve on the year's deposits, built from profit and not from contributed capital. It's provisioned before any distribution."),
    ("Single supplier", "", "Two active sales channels, both with immediate collection. Diversifying the supply origin is a second-year objective."),
  ]),
  ("call", "SCOPE", ["Every contribution should be considered committed for the program's full term. No one is authorized to guarantee a return. **Whoever participates must be in a position to accept the total loss of the amount contributed.**"], "accent"),
  ("result", "PROJECTED ANNUAL RESULT", "USD 164,059",
    "before taxes · 1.37x on requested capital",
    "USD 126,059 after taxes · 24 containers · ", "0.78 USD/kg FOB"),
]

META = {
  "running_left": "PRESSTON · REPLICABLE LINE",
  "running_right": "OPERATING PLAN",
  "footer": "PRESSTON STRATEGIC PARTNERS LLC",
}
